// Generated by https://quicktype.io

export interface IAww {
    data: TopLevelData;
}

export interface TopLevelData {
    children:   Child[];
}

export interface Child {
    data: ChildData;
}

export interface ChildData {
    title:                         string;
    post_hint?:                    PostHint;
    url:                           string;
}

export enum PostHint {
    Image = "image",
}